package com.dallmeier.evidencer.network;

public enum ResultDispatcher {
    LOGIN_SCREEN,
    LOGIN_SUCCESS,
    SCAN_QR_CODE_SCREEN,
    HOME_SCREEN,
    WAITING_ACTIVE_ACCOUNT_SCREEN,
    SHOW_DIALOG_ACCOUNT_ACTIVE_IS_REMOVED,
    SHOW_DIALOG_ACCOUNT_ACTIVE_SUCCESS,
    SHOW_DIALOG_WAITING_ACCOUNT_ACTIVE,
}
